[versions]
agp = "8.8.2"
kotlin = "2.1.10"
jvm = "21"
minSdk = "30"
compileSdk = "35"
targetSdk = "35"
buildTools = "35.0.0"
onnxruntime = "1.29.0"

[libraries]
onnxruntime-android = { module = "com.microsoft.onnxruntime:onnxruntime-android", version.ref = "onnxruntime" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
