"""Fail-closed qualification primitives for the pinned Serbian VITS candidate."""

from .qualification import (
    FINAL_RATE_HZ,
    MODEL_ID,
    NATIVE_RATE_HZ,
    REVISION,
    SPEAKER_ID,
    SPEAKER_LABEL,
    acceptance_eligibility,
    canonical_json,
    chunk_boundaries,
    engine_options,
    generation_identity,
    legal_status,
    preprocess_text,
    resample_22050_to_24000,
    run_gates,
    validate_android_matrix,
    validate_quality_corpus,
    validate_resampler_manifest,
    validate_identity,
    validate_package_entries,
    validate_source_manifest,
)

__all__ = [
    "FINAL_RATE_HZ",
    "MODEL_ID",
    "NATIVE_RATE_HZ",
    "REVISION",
    "SPEAKER_ID",
    "SPEAKER_LABEL",
    "acceptance_eligibility",
    "canonical_json",
    "chunk_boundaries",
    "engine_options",
    "generation_identity",
    "legal_status",
    "preprocess_text",
    "resample_22050_to_24000",
    "run_gates",
    "validate_android_matrix",
    "validate_identity",
    "validate_package_entries",
    "validate_quality_corpus",
    "validate_resampler_manifest",
    "validate_source_manifest",
]
